name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Setup java environment
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3
        with:
          java-version: 17
          distribution: adopt

      - name: Lint, test and build the debug apk
        uses: eskatos/gradle-command-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2
        with:
          gradle-version: 8.14.3
          arguments: check assembleDebug